# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: cats-in-space
    init: |
      cd nx-odyssey
      npm i
    command: |
      npx nx run cats-in-space:serve:development

  - name: shell
    command: |
      cd nx-odyssey
      node --version
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: nx cats in space
    description: nx client
    port: 4200
    onOpen: open-browser
    visibility: public

  - name: cats in space
    description: client
    port: 3000
    onOpen: open-browser
    visibility: public

  - name: nx graph
    description: nx graph
    port: 4211
    onOpen: open-browser
    visibility: public

  - name: gql-server
    description: gql-server
    port: 4000
    onOpen: open-browser
    visibility: public